import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  login_screen_container: {
    flex: 1,
    backgroundColor: "#2c3e50",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  auth0_login_background: {
    backgroundColor: "rgba(255, 255, 255, 0.75)",
    borderRadius: 15,
    padding: 30,
    alignItems: "center",
    width: "100%",
    maxWidth: 300,
  },
  auth0_login_title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#2c3e50",
  },
  subauth0_login_title: {
    fontSize: 20,
    fontFamily: "System",
    marginBottom: 30,
    color: "#414546ff",
  },
  authenticated_homescreen_title: {
    fontSize: 2,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#27ae60",
  },
  email: {
    fontSize: 14,
    color: "#7f8c8d",
    marginBottom: 20,
  },
  loadingText: {
    marginTop: 10,
    color: "#7f8c8d",
  },
  auth0_login_button: {
    fontSize: 20,
    backgroundColor: "#9fa1a3ff",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    elevation: 2,
  },
  backButton: {
    padding: 8,
  },
  backButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  bottomPanel: {
    position: "absolute",
    bottom: 50,
    left: 16,
    right: 16,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    padding: 16,
    borderRadius: 12,
  },
  welcomeText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 4,
  },
  floatingHeader: {
    position: "absolute",
    top: 15,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 10,
    zIndex: 1000,
  },
  floatingHamburgerMenu: {
    backgroundColor: "rgba(255, 255, 255, 0.71)",
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5, // Android shadow
  },

  floatingTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    marginLeft: 20,
  },
  mapsHamburgerIcon: {
    fontSize: 20,
    color: "#333", // Dark color since we have white background
    fontWeight: "bold",
  },
  map: {
    flex: 1,
    width: "100%",
    height: "100%",
  },

  maps_container: {
    flex: 1,
    position: "relative",
  },
  maps_bottom_tab_navigation: {
    backgroundColor: "rgba(0, 0, 0, 0.82)",
    borderTopColor: "transparent",
    borderTopWidth: 0,
    elevation: 0,
    shadowOpacity: 0,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 0,
    position: "absolute",
  },
  locationButton: {
    position: "absolute",
    top : 25,
    right: 20,
    backgroundColor: "rgba(233, 227, 227, 0.8)",
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 1000,
  },
  locationButtonText: {
    fontSize: 24,
  },
  iosLocationButton: {
    position: "absolute",
    top: 85,
    right: 20,
    backgroundColor: "white",
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  iosLocationButtonText: {
    fontSize: 20,
  },
  userOptionsModal: {
    backgroundColor: "white",
    height: 300,
    width: 300,
    borderRadius: 8,
    padding: 30,
    margin: 20,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    top: "30%",
  },
  modalButtons: {
    margin: 5,
    padding: 15,
    borderRadius: 8,
    minHeight: 50,
    width: "80%",
    justifyContent: "center",
    alignItems: "center",
  },
  waypointMenuModalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
  },
  waypointMenuButtonText: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },

  editWaypointModalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
  },
  editWaypointTextInput: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
    minWidth: 200,
    backgroundColor: "white",
  },
  editWaypointButtonText: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  deleteAllWaypointsModalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
  },
  deleteAllWaypointsSubtext: {
    fontSize: 14,
    color: "#666",
    marginBottom: 15,
    textAlign: "center",
  },
  deleteAllWaypointsButtonText: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
});
